version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: currency-flow.com/php
    container_name: currency-flow-app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: currency-flow-app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - currency-flow-app-network

  #Nginx Service
  webserver:
    image: nginx:1.19-alpine
    container_name: currency-flow-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/config/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      -  currency-flow-app-network

  #MySQL Service
  db:
    image: mysql:8
    container_name: currency-flow-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: currency-flow
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: luka
      MYSQL_PASSWORD: passlukapass
      SERVICE_NAME: currency-flow-mysql
      SERVICE_TAGS: dev
    volumes:
      - currency-flow-dbdata:/var/lib/mysql/
      - ./docker/config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      -  currency-flow-app-network

#Docker Networks
networks:
  currency-flow-app-network:
    driver: bridge

#Volumes
volumes:
  currency-flow-dbdata:
    driver: local
